/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.usuario.registroIngreso;

import interfaz.launcher.PrincipalOpciones;
import interfaz.usuario.InterfazInicioUsuario;
import java.awt.BorderLayout;

/**
 *
 * @author Arturo
 */
public class RegistroCrearUserPass extends javax.swing.JPanel {

    /**
     * Creates new form RegistroCrearUserPass
     */
    public RegistroCrearUserPass() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        botonVerContra = new javax.swing.JButton();
        fieldPassword = new javax.swing.JPasswordField();
        labelContraseña = new javax.swing.JLabel();
        labelRepetirContra = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonFinalizar = new javax.swing.JButton();
        fieldRepetirPassword = new javax.swing.JPasswordField();
        botonVerRepContra = new javax.swing.JButton();
        labelErrorInicio = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1300, 570));
        setMinimumSize(new java.awt.Dimension(1300, 570));
        setLayout(new java.awt.BorderLayout());

        base.setBackground(new java.awt.Color(255, 255, 153));
        base.setPreferredSize(new java.awt.Dimension(1300, 570));

        labelTitulo.setFont(new java.awt.Font("Alumni Sans Light", 0, 24)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Creacion de usuario");

        labelUsuario.setText("Usuario");

        botonVerContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVerContraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonVerContraMouseReleased(evt);
            }
        });

        fieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordActionPerformed(evt);
            }
        });

        labelContraseña.setText("Contraseña");

        labelRepetirContra.setText("Repetir Contraseña");

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });

        botonFinalizar.setText("Finalizar");
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });

        fieldRepetirPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRepetirPasswordActionPerformed(evt);
            }
        });

        botonVerRepContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVerRepContraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonVerRepContraMouseReleased(evt);
            }
        });

        labelErrorInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelErrorInicio.setText("dsadsadasdsad");

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addGap(441, 441, 441)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(labelUsuario)
                        .addGap(100, 100, 100)
                        .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(labelContraseña)
                        .addGap(80, 80, 80)
                        .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(botonVerContra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(labelRepetirContra)
                        .addGap(40, 40, 40)
                        .addComponent(fieldRepetirPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(botonVerRepContra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(botonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)
                        .addComponent(botonFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelErrorInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(469, Short.MAX_VALUE))
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(labelTitulo)
                .addGap(8, 8, 8)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelUsuario)
                    .addComponent(fieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelContraseña)
                    .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerContra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRepetirContra)
                    .addComponent(fieldRepetirPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonVerRepContra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonCancelar)
                    .addComponent(botonFinalizar))
                .addGap(18, 18, 18)
                .addComponent(labelErrorInicio)
                .addContainerGap(260, Short.MAX_VALUE))
        );

        add(base, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerContraMousePressed
        // TODO add your handling code here:

        fieldPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_botonVerContraMousePressed

    private void botonVerContraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerContraMouseReleased
        // TODO add your handling code here:
        fieldPassword.setEchoChar('*');
    }//GEN-LAST:event_botonVerContraMouseReleased

    private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasswordActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        InterfazInicioUsuario inicio = new InterfazInicioUsuario();
        inicio.setSize(1300, 570);
        inicio.setLocation(0, 0);

        base.removeAll();
        base.add(inicio, BorderLayout.CENTER);
        base.revalidate();
        base.repaint();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonFinalizarActionPerformed

    private void fieldRepetirPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRepetirPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRepetirPasswordActionPerformed

    private void botonVerRepContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerRepContraMousePressed
        // TODO add your handling code here:

        fieldRepetirPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_botonVerRepContraMousePressed

    private void botonVerRepContraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerRepContraMouseReleased
        // TODO add your handling code here:

        fieldRepetirPassword.setEchoChar('*');
    }//GEN-LAST:event_botonVerRepContraMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JButton botonVerContra;
    private javax.swing.JButton botonVerRepContra;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JPasswordField fieldRepetirPassword;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelErrorInicio;
    private javax.swing.JLabel labelRepetirContra;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
