/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.usuario.registroIngreso;

import clases.personas.Pasajero;
import interfaz.launcher.PrincipalOpciones;
import interfaz.usuario.InterfazInicioUsuario;
import java.awt.BorderLayout;
import logica.Datos;

/**
 *
 * @author Arturo
 */
public class RegistroCrearUserPass extends javax.swing.JPanel {

    /**
     * Creates new form RegistroCrearUserPass
     */
    public RegistroCrearUserPass() {
        initComponents();
    }

    private boolean verificarUser() {

        boolean esRegistrado = false;

        for (int i = 0; i < Datos.getListaUsuariosPrincipal().longitud(); i++) {

            String userActual = fieldUsuario.getText();
            String userBase = Datos.getListaUsuariosPrincipal().obtener(i).getUsuario();

            if (userActual.equals(userBase)) {

                esRegistrado = true;

            }

        }

        return esRegistrado;

    }

    private boolean verificarContraseñas() {

        String contra1 = String.valueOf(fieldPassword.getPassword());
        String contra2 = String.valueOf(fieldRepetirPassword.getPassword());

        boolean contrasIguales = false;

        if (contra1.equals(contra2)) {

            contrasIguales = true;

        }

        return contrasIguales;

    }

    private boolean verificarEspacios() {

        boolean esCompleto = false;

        if (fieldUsuario.getText().isBlank() == false && String.valueOf(fieldPassword.getPassword()).isBlank() == false
                && String.valueOf(fieldRepetirPassword.getPassword()).isBlank() == false) {

            esCompleto = true;

        }

        return esCompleto;
    }

    private void finalizarCrearUser() {

        Pasajero userNew = new Pasajero();

        userNew = Datos.getTemporal();

        userNew.setUsuario(fieldUsuario.getText());
        userNew.setPassword(String.valueOf(fieldPassword.getPassword()));

        Datos.getListaUsuariosPrincipal().insertarFinLista(userNew);

        Pasajero limpiar = new Pasajero();

        Datos.setTemporal(limpiar);

    }

    private void cambiarPantalla() {
        InterfazInicioUsuario inicio = new InterfazInicioUsuario();
        inicio.setSize(1300, 570);
        inicio.setLocation(0, 0);

        base.removeAll();
        base.add(inicio, BorderLayout.CENTER);
        base.revalidate();
        base.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogoRegistro = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        base = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        labelContraseña = new javax.swing.JLabel();
        labelRepetirContra = new javax.swing.JLabel();
        fieldRepetirPassword = new javax.swing.JPasswordField();
        botonCancelar = new javax.swing.JButton();
        botonFinalizar = new javax.swing.JButton();
        botonVerContra = new javax.swing.JButton();
        botonVerRepContra = new javax.swing.JButton();
        labelError = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();

        dialogoRegistro.setSize(new java.awt.Dimension(400, 300));

        jLabel1.setText("Registro exitoso");

        javax.swing.GroupLayout dialogoRegistroLayout = new javax.swing.GroupLayout(dialogoRegistro.getContentPane());
        dialogoRegistro.getContentPane().setLayout(dialogoRegistroLayout);
        dialogoRegistroLayout.setHorizontalGroup(
            dialogoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoRegistroLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        dialogoRegistroLayout.setVerticalGroup(
            dialogoRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dialogoRegistroLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        setMaximumSize(new java.awt.Dimension(1300, 570));
        setMinimumSize(new java.awt.Dimension(1300, 570));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        base.setBackground(new java.awt.Color(255, 255, 153));
        base.setOpaque(false);
        base.setPreferredSize(new java.awt.Dimension(1300, 570));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Alumni Sans Light", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Creacion de usuario");
        jPanel1.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setText("Usuario");
        jPanel1.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        jPanel1.add(fieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 220, -1));

        fieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 220, -1));

        labelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        labelContraseña.setText("Contraseña");
        jPanel1.add(labelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        labelRepetirContra.setForeground(new java.awt.Color(255, 255, 255));
        labelRepetirContra.setText("Repetir Contraseña");
        jPanel1.add(labelRepetirContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        fieldRepetirPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldRepetirPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(fieldRepetirPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 220, -1));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, -1));

        botonFinalizar.setText("Finalizar");
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(botonFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 80, -1));

        botonVerContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVerContraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonVerContraMouseReleased(evt);
            }
        });
        jPanel1.add(botonVerContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 20, 20));

        botonVerRepContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVerRepContraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonVerRepContraMouseReleased(evt);
            }
        });
        jPanel1.add(botonVerRepContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 20, 20));

        labelError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelError.setText(".");
        jPanel1.add(labelError, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 360, -1));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/fondoIngresoEmpresa.png"))); // NOI18N
        jPanel1.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addGap(423, 423, 423)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        add(base, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonVerContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerContraMousePressed
        // TODO add your handling code here:

        fieldPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_botonVerContraMousePressed

    private void botonVerContraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerContraMouseReleased
        // TODO add your handling code here:
        fieldPassword.setEchoChar('*');
    }//GEN-LAST:event_botonVerContraMouseReleased

    private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasswordActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        InterfazInicioUsuario inicio = new InterfazInicioUsuario();
        inicio.setSize(1300, 570);
        inicio.setLocation(0, 0);

        base.removeAll();
        base.add(inicio, BorderLayout.CENTER);
        base.revalidate();
        base.repaint();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
        // TODO add your handling code here:

        if (verificarEspacios() == true) {

            if (verificarUser() == true) {

                labelError.setText("Usuario ya está en uso");

            }

            if (verificarContraseñas() == false) {

                labelError.setText("Las contraseñas no coinciden");

            }

            if (verificarUser() == false && verificarContraseñas() == true) {

                finalizarCrearUser();
                cambiarPantalla();

                dialogoRegistro.setSize(400, 300);
                dialogoRegistro.setResizable(false);
                dialogoRegistro.setAlwaysOnTop(true);
                dialogoRegistro.setLocationRelativeTo(null);
                dialogoRegistro.setVisible(true);

            }

        }else{
            labelError.setText("Todos los espacios deben ser diligenciados");
        }


    }//GEN-LAST:event_botonFinalizarActionPerformed

    private void fieldRepetirPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldRepetirPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldRepetirPasswordActionPerformed

    private void botonVerRepContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerRepContraMousePressed
        // TODO add your handling code here:

        fieldRepetirPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_botonVerRepContraMousePressed

    private void botonVerRepContraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerRepContraMouseReleased
        // TODO add your handling code here:

        fieldRepetirPassword.setEchoChar('*');
    }//GEN-LAST:event_botonVerRepContraMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JButton botonVerContra;
    private javax.swing.JButton botonVerRepContra;
    private javax.swing.JDialog dialogoRegistro;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JPasswordField fieldRepetirPassword;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelError;
    private javax.swing.JLabel labelRepetirContra;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
