/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.usuario;

import interfaz.launcher.PrincipalOpciones;
import interfaz.usuario.registroIngreso.InterIngreso;
import interfaz.usuario.registroIngreso.RegistroClientes;
import java.awt.BorderLayout;

/**
 *
 * @author Arturo
 */
public class InterfazInicioUsuario extends javax.swing.JPanel {

    /**
     * Creates new form InterfazInicio
     */
    public InterfazInicioUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonUsuarios = new javax.swing.JButton();
        botonAerolinea = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        botonIngreso = new javax.swing.JButton();
        botonRegistro = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1300, 570));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1300, 570));
        setLayout(new java.awt.BorderLayout());

        base.setBackground(new java.awt.Color(153, 255, 153));
        base.setMinimumSize(new java.awt.Dimension(1300, 570));
        base.setOpaque(false);
        base.setPreferredSize(new java.awt.Dimension(1300, 570));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonUsuarios.setText("Usuarios");
        botonUsuarios.setEnabled(false);
        jPanel1.add(botonUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 219, 84));

        botonAerolinea.setText("Aerolinea");
        botonAerolinea.setEnabled(false);
        jPanel1.add(botonAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 219, 84));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/fondoIngresoEmpresa.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel3.setBackground(new java.awt.Color(51, 255, 102));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonIngreso.setText("ingresar");
        botonIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIngresoActionPerformed(evt);
            }
        });
        jPanel3.add(botonIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 180, 70));

        botonRegistro.setText("registrarse");
        botonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroActionPerformed(evt);
            }
        });
        jPanel3.add(botonRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 180, 70));

        botonCerrar.setText("X");
        botonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarActionPerformed(evt);
            }
        });
        jPanel3.add(botonCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 40, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/fondoMenuPeque.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(448, Short.MAX_VALUE))
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))))
        );

        add(base, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIngresoActionPerformed
        // TODO add your handling code here:

        InterIngreso interfazIngreso = new InterIngreso();
        interfazIngreso.setSize(1300, 570);
        interfazIngreso.setLocation(0, 0);

        base.removeAll();
        base.add(interfazIngreso, BorderLayout.CENTER);
        base.revalidate();
        base.repaint();

    }//GEN-LAST:event_botonIngresoActionPerformed

    private void botonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroActionPerformed
        // TODO add your handling code here:
        RegistroClientes interfazRegistro = new RegistroClientes();
        interfazRegistro.setSize(1300, 570);
        interfazRegistro.setLocation(0, 0);

        base.removeAll();
        base.add(interfazRegistro, BorderLayout.CENTER);
        base.revalidate();
        base.repaint();
    }//GEN-LAST:event_botonRegistroActionPerformed

    private void botonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarActionPerformed
        // TODO add your handling code here:
        PrincipalOpciones inicio = new PrincipalOpciones();
        inicio.setSize(1300, 570);
        inicio.setLocation(0, 0);

        base.removeAll();
        base.add(inicio, BorderLayout.CENTER);
        base.revalidate();
        base.repaint();

    }//GEN-LAST:event_botonCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JButton botonAerolinea;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonIngreso;
    private javax.swing.JButton botonRegistro;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
