/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.interfazMenuClientes.opciones.registro;

import interfaz.interfazMenuClientes.*;
import interfaz.interfazMenuPrincipal.*;
import java.awt.Color;
import java.awt.Image;
import java.awt.geom.RoundRectangle2D;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author Arturo
 */
public class InterRegistrar extends javax.swing.JFrame {

    /**
     * Creates new form menuPrincipal
     */
    public InterRegistrar() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setShape(new RoundRectangle2D.Double(0, 0, 1300, 1600, 50, 50));

        //this.setSize(300, 200);
    }

    //metodos Propios
    public void cerrarPrograma() {

        System.exit(0);

    }

    public void minimizarPrograma() {

        this.setState(this.ICONIFIED);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaDias1 = new javax.swing.JComboBox<>();
        labelDia1 = new javax.swing.JLabel();
        labelDia = new javax.swing.JLabel();
        labelAño = new javax.swing.JLabel();
        labelMes = new javax.swing.JLabel();
        listaDias = new javax.swing.JComboBox<>();
        listaMeses = new javax.swing.JComboBox<>();
        listaAños = new javax.swing.JComboBox<>();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        botonAerolinea = new javax.swing.JButton();
        botonClientes = new javax.swing.JButton();
        panelOpcionesVentana = new javax.swing.JPanel();
        botonMinimizar = new javax.swing.JButton();
        botonCerrar = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listaDias1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula de ciudadania", "Pasaporte", "Documento de identificacion Extranjero" }));
        listaDias1.setBorder(null);
        listaDias1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDias1ActionPerformed(evt);
            }
        });
        getContentPane().add(listaDias1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 220, -1));

        labelDia1.setText("Tipo de Documento");
        getContentPane().add(labelDia1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, -1));

        labelDia.setText("Dia de nacimiento");
        getContentPane().add(labelDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, -1, -1));

        labelAño.setText("Año de nacimiento");
        getContentPane().add(labelAño, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        labelMes.setText("Mes de nacimiento");
        getContentPane().add(labelMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, -1, -1));

        listaDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        listaDias.setBorder(null);
        listaDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDiasActionPerformed(evt);
            }
        });
        getContentPane().add(listaDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 400, 60, -1));
        listaDias.getAccessibleContext().setAccessibleDescription("");

        listaMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        listaMeses.setBorder(null);
        listaMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMesesActionPerformed(evt);
            }
        });
        getContentPane().add(listaMeses, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 60, -1));

        listaAños.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        listaAños.setBorder(null);
        listaAños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAñosActionPerformed(evt);
            }
        });
        getContentPane().add(listaAños, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 60, -1));

        botonAerolinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/opcionAirline.png"))); // NOI18N
        botonAerolinea.setBorderPainted(false);
        botonAerolinea.setContentAreaFilled(false);
        botonAerolinea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonAerolineaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonAerolineaMouseExited(evt);
            }
        });

        botonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/opcionUsuarios.png"))); // NOI18N
        botonClientes.setBorderPainted(false);
        botonClientes.setContentAreaFilled(false);
        botonClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonClientesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonClientesMouseExited(evt);
            }
        });

        jLayeredPane1.setLayer(botonAerolinea, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(botonClientes, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(botonAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(botonClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(botonAerolinea, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 340, 240));

        panelOpcionesVentana.setOpaque(false);

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/botonMinimizar.png"))); // NOI18N
        botonMinimizar.setBorderPainted(false);
        botonMinimizar.setContentAreaFilled(false);
        botonMinimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonMinimizarMouseExited(evt);
            }
        });

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/botonCerrar.png"))); // NOI18N
        botonCerrar.setBorderPainted(false);
        botonCerrar.setContentAreaFilled(false);
        botonCerrar.setPreferredSize(new java.awt.Dimension(39, 22));
        botonCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCerrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                botonCerrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                botonCerrarMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesVentanaLayout = new javax.swing.GroupLayout(panelOpcionesVentana);
        panelOpcionesVentana.setLayout(panelOpcionesVentanaLayout);
        panelOpcionesVentanaLayout.setHorizontalGroup(
            panelOpcionesVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesVentanaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(botonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        panelOpcionesVentanaLayout.setVerticalGroup(
            panelOpcionesVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesVentanaLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(panelOpcionesVentanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonMinimizar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelOpcionesVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 0, 120, 30));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/baseTest2.png"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCerrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseExited
        // TODO add your handling code here:

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/botonCerrar.png")));
    }//GEN-LAST:event_botonCerrarMouseExited

    private void botonCerrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseEntered
        // TODO add your handling code here:

        botonCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/botonCerrar2.png")));
    }//GEN-LAST:event_botonCerrarMouseEntered

    private void botonCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCerrarMouseClicked
        // TODO add your handling code here:
        cerrarPrograma();
    }//GEN-LAST:event_botonCerrarMouseClicked

    private void botonMinimizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseExited
        // TODO add your handling code here:

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/botonMinimizar.png")));
    }//GEN-LAST:event_botonMinimizarMouseExited

    private void botonMinimizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseEntered
        // TODO add your handling code here:

        botonMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/botonMinimizar2.png")));
    }//GEN-LAST:event_botonMinimizarMouseEntered

    private void botonMinimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonMinimizarMouseClicked
        // TODO add your handling code here:
        minimizarPrograma();
    }//GEN-LAST:event_botonMinimizarMouseClicked

    private void botonClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClientesMouseEntered
        // TODO add your handling code here:
        botonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/opcionUsuarios2.png")));
    }//GEN-LAST:event_botonClientesMouseEntered

    private void botonClientesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonClientesMouseExited
        // TODO add your handling code here:
        botonClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/opcionUsuarios.png")));
    }//GEN-LAST:event_botonClientesMouseExited

    private void botonAerolineaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAerolineaMouseExited
        // TODO add your handling code here:
        botonAerolinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/opcionAirline.png")));
    }//GEN-LAST:event_botonAerolineaMouseExited

    private void botonAerolineaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonAerolineaMouseEntered
        // TODO add your handling code here:
        botonAerolinea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/opcionAirline2.png")));
    }//GEN-LAST:event_botonAerolineaMouseEntered

    private void listaDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDiasActionPerformed

    private void listaMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaMesesActionPerformed

    private void listaAñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaAñosActionPerformed

    private void listaDias1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDias1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDias1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAerolinea;
    private javax.swing.JButton botonCerrar;
    private javax.swing.JButton botonClientes;
    private javax.swing.JButton botonMinimizar;
    private javax.swing.JLabel fondo;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLabel labelAño;
    private javax.swing.JLabel labelDia;
    private javax.swing.JLabel labelDia1;
    private javax.swing.JLabel labelMes;
    private javax.swing.JComboBox<String> listaAños;
    private javax.swing.JComboBox<String> listaDias;
    private javax.swing.JComboBox<String> listaDias1;
    private javax.swing.JComboBox<String> listaMeses;
    private javax.swing.JPanel panelOpcionesVentana;
    // End of variables declaration//GEN-END:variables
}
