/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package interfaz.aerolinea.interfazAerolinea.opciones;

import interfaz.usuario.interfazUsuario.*;

/**
 *
 * @author Arturo
 */
public class MiInfoEmpleados extends javax.swing.JPanel {

    /** Creates new form MiInfoUsuarios */
    public MiInfoEmpleados() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNumeroDeEmpleado = new javax.swing.JPanel();
        labelTipoDoc1 = new javax.swing.JLabel();
        fieldNombres = new javax.swing.JTextField();
        fieldApellidos = new javax.swing.JTextField();
        labelNumeroDoc1 = new javax.swing.JLabel();
        labelTipoDoc = new javax.swing.JLabel();
        listaTiposDoc = new javax.swing.JComboBox<>();
        labelNumeroDoc = new javax.swing.JLabel();
        fieldNumeroDocumento1 = new javax.swing.JTextField();
        labelFechaNacimiento = new javax.swing.JLabel();
        listaAños = new javax.swing.JComboBox<>();
        listaMeses = new javax.swing.JComboBox<>();
        listaDias = new javax.swing.JComboBox<>();
        labelNumeroDoc2 = new javax.swing.JLabel();
        fieldNumeroDocumento2 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(1010, 558));
        setLayout(new java.awt.BorderLayout());

        labelNumeroDeEmpleado.setBackground(new java.awt.Color(51, 255, 204));
        labelNumeroDeEmpleado.setMinimumSize(new java.awt.Dimension(1010, 558));
        labelNumeroDeEmpleado.setPreferredSize(new java.awt.Dimension(1010, 558));

        labelTipoDoc1.setText("Nombres");

        fieldNombres.setEnabled(false);

        fieldApellidos.setEnabled(false);

        labelNumeroDoc1.setText("Apellidos");

        labelTipoDoc.setText("Tipo de Documento");

        listaTiposDoc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula de ciudadania", "Pasaporte", "Documento de identificacion Extranjero" }));
        listaTiposDoc.setBorder(null);
        listaTiposDoc.setEnabled(false);
        listaTiposDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaTiposDocActionPerformed(evt);
            }
        });

        labelNumeroDoc.setText("Numero de Documento");

        fieldNumeroDocumento1.setBorder(null);
        fieldNumeroDocumento1.setEnabled(false);
        fieldNumeroDocumento1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumeroDocumento1ActionPerformed(evt);
            }
        });

        labelFechaNacimiento.setText("Fecha de nacimiento");

        listaAños.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1900", "1901", "1902", "1903", "1904", "1905", "1906", "1907", "1908", "1909", "1910", "1911", "1912", "1913", "1914", "1915", "1916", "1917", "1918", "1919", "1920", "1921", "1922", "1923", "1924", "1925", "1926", "1927", "1928", "1929", "1930", "1931", "1932", "1933", "1934", "1935", "1936", "1937", "1938", "1939", "1940", "1941", "1942", "1943", "1944", "1945", "1946", "1947", "1948", "1949", "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022" }));
        listaAños.setBorder(null);
        listaAños.setEnabled(false);
        listaAños.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaAñosActionPerformed(evt);
            }
        });

        listaMeses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        listaMeses.setBorder(null);
        listaMeses.setEnabled(false);
        listaMeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaMesesActionPerformed(evt);
            }
        });

        listaDias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        listaDias.setBorder(null);
        listaDias.setEnabled(false);
        listaDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaDiasActionPerformed(evt);
            }
        });

        labelNumeroDoc2.setText("Numero de Empleado");

        fieldNumeroDocumento2.setBorder(null);
        fieldNumeroDocumento2.setEnabled(false);
        fieldNumeroDocumento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumeroDocumento2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout labelNumeroDeEmpleadoLayout = new javax.swing.GroupLayout(labelNumeroDeEmpleado);
        labelNumeroDeEmpleado.setLayout(labelNumeroDeEmpleadoLayout);
        labelNumeroDeEmpleadoLayout.setHorizontalGroup(
            labelNumeroDeEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelNumeroDeEmpleadoLayout.createSequentialGroup()
                .addGap(335, 335, 335)
                .addGroup(labelNumeroDeEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(labelNumeroDeEmpleadoLayout.createSequentialGroup()
                        .addComponent(labelTipoDoc1)
                        .addGap(91, 91, 91)
                        .addComponent(fieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(labelNumeroDeEmpleadoLayout.createSequentialGroup()
                        .addComponent(labelNumeroDoc1)
                        .addGap(91, 91, 91)
                        .addComponent(fieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(labelNumeroDeEmpleadoLayout.createSequentialGroup()
                        .addComponent(labelTipoDoc)
                        .addGap(35, 35, 35)
                        .addComponent(listaTiposDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(labelNumeroDeEmpleadoLayout.createSequentialGroup()
                        .addComponent(labelFechaNacimiento)
                        .addGap(30, 30, 30)
                        .addComponent(listaAños, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(listaMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(listaDias, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(labelNumeroDeEmpleadoLayout.createSequentialGroup()
                        .addGroup(labelNumeroDeEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNumeroDoc)
                            .addComponent(labelNumeroDoc2))
                        .addGap(14, 14, 14)
                        .addGroup(labelNumeroDeEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldNumeroDocumento2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fieldNumeroDocumento1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(315, Short.MAX_VALUE))
        );
        labelNumeroDeEmpleadoLayout.setVerticalGroup(
            labelNumeroDeEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(labelNumeroDeEmpleadoLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(labelNumeroDeEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoDoc1)
                    .addComponent(fieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(labelNumeroDeEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumeroDoc1)
                    .addComponent(fieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(labelNumeroDeEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTipoDoc)
                    .addComponent(listaTiposDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(labelNumeroDeEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNumeroDoc)
                    .addComponent(fieldNumeroDocumento1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(labelNumeroDeEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumeroDoc2)
                    .addComponent(fieldNumeroDocumento2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(labelNumeroDeEmpleadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFechaNacimiento)
                    .addComponent(listaAños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(listaDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        add(labelNumeroDeEmpleado, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void listaTiposDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaTiposDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaTiposDocActionPerformed

    private void listaAñosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaAñosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaAñosActionPerformed

    private void listaMesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaMesesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaMesesActionPerformed

    private void listaDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listaDiasActionPerformed

    private void fieldNumeroDocumento1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumeroDocumento1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumeroDocumento1ActionPerformed

    private void fieldNumeroDocumento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumeroDocumento2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumeroDocumento2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldApellidos;
    private javax.swing.JTextField fieldNombres;
    private javax.swing.JTextField fieldNumeroDocumento1;
    private javax.swing.JTextField fieldNumeroDocumento2;
    private javax.swing.JLabel labelFechaNacimiento;
    private javax.swing.JPanel labelNumeroDeEmpleado;
    private javax.swing.JLabel labelNumeroDoc;
    private javax.swing.JLabel labelNumeroDoc1;
    private javax.swing.JLabel labelNumeroDoc2;
    private javax.swing.JLabel labelTipoDoc;
    private javax.swing.JLabel labelTipoDoc1;
    private javax.swing.JComboBox<String> listaAños;
    private javax.swing.JComboBox<String> listaDias;
    private javax.swing.JComboBox<String> listaMeses;
    private javax.swing.JComboBox<String> listaTiposDoc;
    // End of variables declaration//GEN-END:variables

}
