/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package interfaz.aerolinea.interfazAerolinea.opciones;

import interfaz.aerolinea.interfazAerolinea.opcionesVehiculos.opcionAutomoviles;
import interfaz.aerolinea.interfazAerolinea.opcionesVehiculos.opcionAviones;
import interfaz.aerolinea.interfazAerolinea.opcionesVehiculos.opcionBuses;
import interfaz.aerolinea.interfazAerolinea.opcionesVehiculos.opcionCamiones;
import java.awt.BorderLayout;

/**
 *
 * @author Arturo
 */
public class PanelBaseVehiculos extends javax.swing.JPanel {

    /**
     * Creates new form PanelBaseVehiculos
     */
    public PanelBaseVehiculos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelData = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonAutomoviles = new javax.swing.JButton();
        botonBuses = new javax.swing.JButton();
        botonCamion = new javax.swing.JButton();
        botonAvion = new javax.swing.JButton();
        dataB = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(1010, 558));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        panelData.setBackground(new java.awt.Color(102, 255, 0));
        panelData.setMinimumSize(new java.awt.Dimension(1010, 558));
        panelData.setOpaque(false);
        panelData.setPreferredSize(new java.awt.Dimension(1010, 558));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setOpaque(false);

        botonAutomoviles.setText("Automoviles");
        botonAutomoviles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAutomovilesActionPerformed(evt);
            }
        });

        botonBuses.setText("Bus");
        botonBuses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBusesActionPerformed(evt);
            }
        });

        botonCamion.setText("Camion");
        botonCamion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCamionActionPerformed(evt);
            }
        });

        botonAvion.setText("Avion");
        botonAvion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAvionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(botonAutomoviles)
                .addGap(18, 18, 18)
                .addComponent(botonBuses)
                .addGap(18, 18, 18)
                .addComponent(botonCamion)
                .addGap(18, 18, 18)
                .addComponent(botonAvion)
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonAutomoviles)
                    .addComponent(botonBuses)
                    .addComponent(botonCamion)
                    .addComponent(botonAvion))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        dataB.setMaximumSize(new java.awt.Dimension(1004, 474));
        dataB.setMinimumSize(new java.awt.Dimension(1004, 474));
        dataB.setOpaque(false);
        dataB.setPreferredSize(new java.awt.Dimension(1004, 474));

        javax.swing.GroupLayout dataBLayout = new javax.swing.GroupLayout(dataB);
        dataB.setLayout(dataBLayout);
        dataBLayout.setHorizontalGroup(
            dataBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dataBLayout.setVerticalGroup(
            dataBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 474, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelDataLayout = new javax.swing.GroupLayout(panelData);
        panelData.setLayout(panelDataLayout);
        panelDataLayout.setHorizontalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataB, javax.swing.GroupLayout.PREFERRED_SIZE, 998, Short.MAX_VALUE)
                    .addGroup(panelDataLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 362, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelDataLayout.setVerticalGroup(
            panelDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dataB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(panelData, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonAutomovilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAutomovilesActionPerformed
        // TODO add your handling code here:
        opcionAutomoviles interPanelAutomoviles = new opcionAutomoviles();
        interPanelAutomoviles.setSize(1004, 474);
        interPanelAutomoviles.setLocation(0, 0);

        dataB.removeAll();
        dataB.add(interPanelAutomoviles, BorderLayout.CENTER);
        dataB.revalidate();
        dataB.repaint();
    }//GEN-LAST:event_botonAutomovilesActionPerformed

    private void botonBusesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBusesActionPerformed
        // TODO add your handling code here:
        opcionBuses interPanelBus = new opcionBuses();
        interPanelBus.setSize(1004, 474);
        interPanelBus.setLocation(0, 0);

        dataB.removeAll();
        dataB.add(interPanelBus, BorderLayout.CENTER);
        dataB.revalidate();
        dataB.repaint();
    }//GEN-LAST:event_botonBusesActionPerformed

    private void botonCamionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCamionActionPerformed
        // TODO add your handling code here:
        opcionCamiones interPanelCamion = new opcionCamiones();
        interPanelCamion.setSize(1004, 474);
        interPanelCamion.setLocation(0, 0);

        dataB.removeAll();
        dataB.add(interPanelCamion, BorderLayout.CENTER);
        dataB.revalidate();
        dataB.repaint();
    }//GEN-LAST:event_botonCamionActionPerformed

    private void botonAvionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAvionActionPerformed
        // TODO add your handling code here:
        opcionAviones interPanelAviones = new opcionAviones();
        interPanelAviones.setSize(1004, 474);
        interPanelAviones.setLocation(0, 0);

        dataB.removeAll();
        dataB.add(interPanelAviones, BorderLayout.CENTER);
        dataB.revalidate();
        dataB.repaint();
    }//GEN-LAST:event_botonAvionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAutomoviles;
    private javax.swing.JButton botonAvion;
    private javax.swing.JButton botonBuses;
    private javax.swing.JButton botonCamion;
    private javax.swing.JPanel dataB;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelData;
    // End of variables declaration//GEN-END:variables
}
