/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.usuario.interfazUsuario;

import interfaz.launcher.PrincipalOpciones;
import java.awt.BorderLayout;

/**
 *
 * @author Arturo
 */
public class BaseInterfazUsuario extends javax.swing.JPanel {

    /**
     * Creates new form BaseInterfazUsuario
     */
    public BaseInterfazUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        panelData = new javax.swing.JPanel();
        panelOpciones = new javax.swing.JPanel();
        botonInfo = new javax.swing.JButton();
        botonContactos = new javax.swing.JButton();
        botonVuelo = new javax.swing.JButton();
        panelDesconectar = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1300, 570));
        setMinimumSize(new java.awt.Dimension(1300, 570));
        setLayout(new java.awt.BorderLayout());

        base.setBackground(new java.awt.Color(255, 255, 153));
        base.setPreferredSize(new java.awt.Dimension(1300, 570));

        panelData.setMaximumSize(new java.awt.Dimension(1010, 558));
        panelData.setMinimumSize(new java.awt.Dimension(1010, 558));
        panelData.setPreferredSize(new java.awt.Dimension(1010, 558));
        panelData.setLayout(new java.awt.BorderLayout());

        panelOpciones.setPreferredSize(new java.awt.Dimension(260, 160));

        botonInfo.setText("Mi informacion");
        botonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInfoActionPerformed(evt);
            }
        });

        botonContactos.setText("Contactos de Emergencia");
        botonContactos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContactosActionPerformed(evt);
            }
        });

        botonVuelo.setText("Mi vuelo");
        botonVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVueloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelOpcionesLayout = new javax.swing.GroupLayout(panelOpciones);
        panelOpciones.setLayout(panelOpcionesLayout);
        panelOpcionesLayout.setHorizontalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(botonInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(73, 73, 73))
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonContactos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(botonVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelOpcionesLayout.setVerticalGroup(
            panelOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOpcionesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botonInfo)
                .addGap(18, 18, 18)
                .addComponent(botonContactos)
                .addGap(18, 18, 18)
                .addComponent(botonVuelo)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        panelDesconectar.setPreferredSize(new java.awt.Dimension(260, 100));

        jButton4.setText("Desconectarse");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDesconectarLayout = new javax.swing.GroupLayout(panelDesconectar);
        panelDesconectar.setLayout(panelDesconectarLayout);
        panelDesconectarLayout.setHorizontalGroup(
            panelDesconectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDesconectarLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelDesconectarLayout.setVerticalGroup(
            panelDesconectarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDesconectarLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelOpciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDesconectar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelData, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(panelOpciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelDesconectar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        add(base, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInfoActionPerformed
        // TODO add your handling code here:
        MiInfoUsuarios infoUsuario = new MiInfoUsuarios();
        infoUsuario.setSize(1010, 558);
        infoUsuario.setLocation(0, 0);

        panelData.removeAll();
        panelData.add(infoUsuario, BorderLayout.CENTER);
        panelData.revalidate();
        panelData.repaint();
    }//GEN-LAST:event_botonInfoActionPerformed

    private void botonContactosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContactosActionPerformed
        // TODO add your handling code here:
        
        ContactosEmergenciaUsuarios contactoUsuario = new ContactosEmergenciaUsuarios();
        contactoUsuario.setSize(1010, 558);
        contactoUsuario.setLocation(0, 0);

        panelData.removeAll();
        panelData.add(contactoUsuario, BorderLayout.CENTER);
        panelData.revalidate();
        panelData.repaint();
    }//GEN-LAST:event_botonContactosActionPerformed

    private void botonVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVueloActionPerformed
        // TODO add your handling code here:
        
        MiVueloUsuarios vueloUsuario = new MiVueloUsuarios();
        vueloUsuario.setSize(1010, 558);
        vueloUsuario.setLocation(0, 0);

        panelData.removeAll();
        panelData.add(vueloUsuario, BorderLayout.CENTER);
        panelData.revalidate();
        panelData.repaint();
    }//GEN-LAST:event_botonVueloActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        PrincipalOpciones inicio = new PrincipalOpciones();
        inicio.setSize(1300, 570);
        inicio.setLocation(0, 0);

        base.removeAll();
        base.add(inicio, BorderLayout.CENTER);
        base.revalidate();
        base.repaint();
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JButton botonContactos;
    private javax.swing.JButton botonInfo;
    private javax.swing.JButton botonVuelo;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel panelData;
    private javax.swing.JPanel panelDesconectar;
    private javax.swing.JPanel panelOpciones;
    // End of variables declaration//GEN-END:variables
}
