/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.aerolinea.ingreso;

import estructuras.aerolinea.ListaEnlazadaEmpleados;
import interfaz.aerolinea.interfazAerolinea.base.BaseInterfazEmpleados;
import interfaz.launcher.PrincipalOpciones;
import java.awt.BorderLayout;
import logica.Datos;

/**
 *
 * @author Arturo
 */
public class InterIngresoAerolinea extends javax.swing.JPanel {

    /**
     * Creates new form Ingreso
     */
    public InterIngresoAerolinea() {
        initComponents();

    }

    private boolean verificacionUsuario() {

        ListaEnlazadaEmpleados lista = new ListaEnlazadaEmpleados();

        lista = Datos.getListaEmpleadosPrincipal();

        boolean esIngresoAprobado = false;

        for (int i = 0; i < lista.longitud(); i++) {

            String usuarioActual = lista.obtener(i).getUsuario();
            String contraActual = lista.obtener(i).getPassword();

            if (usuarioActual.equals(fieldUsuario.getText()) && (String.valueOf(contraActual)).equals(String.valueOf(fieldPassword.getPassword()))) {

                System.out.println("si");
                Datos.setIndiceEmpleado(i);
                esIngresoAprobado = true;

                break;

            } else {

                System.out.println("no");
                esIngresoAprobado = false;

            }

        }

        return esIngresoAprobado;
    }

    private boolean verificarEspacios() {

        boolean espaciosLlenos;

        if (fieldUsuario.getText().isEmpty()
                || String.valueOf(fieldPassword.getPassword()).isEmpty()) {

            espaciosLlenos = false;
        } else {
            espaciosLlenos = true;
        }

        return espaciosLlenos;
    }

    private void ingresar() {

        BaseInterfazEmpleados InterfazEmpleado = new BaseInterfazEmpleados();
        InterfazEmpleado.setSize(1300, 570);
        InterfazEmpleado.setLocation(0, 0);

        base.removeAll();
        base.add(InterfazEmpleado, BorderLayout.CENTER);
        base.revalidate();
        base.repaint();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        fieldUsuario = new javax.swing.JTextField();
        fieldPassword = new javax.swing.JPasswordField();
        labelContraseña = new javax.swing.JLabel();
        botonCancelar = new javax.swing.JButton();
        botonFinalizar = new javax.swing.JButton();
        botonVerContra = new javax.swing.JButton();
        labelErrorInicio = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1300, 570));
        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        base.setBackground(new java.awt.Color(255, 255, 153));
        base.setMinimumSize(new java.awt.Dimension(1300, 570));
        base.setOpaque(false);
        base.setPreferredSize(new java.awt.Dimension(1300, 570));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Alumni Sans Light", 0, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Ingreso Empleados");
        jPanel1.add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        labelUsuario.setBackground(new java.awt.Color(255, 255, 255));
        labelUsuario.setForeground(new java.awt.Color(255, 255, 255));
        labelUsuario.setText("Usuario");
        jPanel1.add(labelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        jPanel1.add(fieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 220, -1));

        fieldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(fieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 220, -1));

        labelContraseña.setBackground(new java.awt.Color(255, 255, 255));
        labelContraseña.setForeground(new java.awt.Color(255, 255, 255));
        labelContraseña.setText("Contraseña");
        jPanel1.add(labelContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(botonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 80, -1));

        botonFinalizar.setText("Ingresar");
        botonFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(botonFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 80, -1));

        botonVerContra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonVerContraMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonVerContraMouseReleased(evt);
            }
        });
        botonVerContra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVerContraActionPerformed(evt);
            }
        });
        jPanel1.add(botonVerContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 20, 20));

        labelErrorInicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelErrorInicio.setText(".");
        jPanel1.add(labelErrorInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 450, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/fondoIngresoEmpresa.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                .addContainerGap(423, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(423, 423, 423))
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        add(base, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        PrincipalOpciones inicio = new PrincipalOpciones();
        inicio.setSize(1300, 570);
        inicio.setLocation(0, 0);

        base.removeAll();
        base.add(inicio, BorderLayout.CENTER);
        base.revalidate();
        base.repaint();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFinalizarActionPerformed
        // TODO add your handling code here:
        boolean esIngreso = verificacionUsuario();
        boolean esCompleto = verificarEspacios();

        if (esCompleto == false) {

            labelErrorInicio.setText("Todos los espacios deben estar diligenciados");

        } else {

            if (esIngreso == true) {
                ingresar();
            } else {

                labelErrorInicio.setText("Usuario y/o contraseña incorrectos");

            }
        }

    }//GEN-LAST:event_botonFinalizarActionPerformed

    private void fieldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldPasswordActionPerformed

    private void botonVerContraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerContraMousePressed
        // TODO add your handling code here:

        fieldPassword.setEchoChar((char) 0);
    }//GEN-LAST:event_botonVerContraMousePressed

    private void botonVerContraMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonVerContraMouseReleased
        // TODO add your handling code here:
        fieldPassword.setEchoChar('*');
    }//GEN-LAST:event_botonVerContraMouseReleased

    private void botonVerContraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVerContraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonVerContraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonFinalizar;
    private javax.swing.JButton botonVerContra;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelErrorInicio;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    // End of variables declaration//GEN-END:variables
}
