package interfaz.launcher;

import interfaz.aerolinea.ingreso.InterIngresoAerolinea;
import interfaz.usuario.InterfazInicioUsuario;
import interfaz.usuario.registroIngreso.InterIngreso;
import java.awt.BorderLayout;

/**
 *
 * @author Arturo
 */
public class PrincipalOpciones extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public PrincipalOpciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        botonUsuarios = new javax.swing.JButton();
        botonAerolinea = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1300, 570));
        setMinimumSize(new java.awt.Dimension(1300, 570));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1300, 570));
        setLayout(new java.awt.BorderLayout());

        base.setBackground(new java.awt.Color(153, 255, 153));
        base.setOpaque(false);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonUsuarios.setText("Usuarios");
        botonUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(botonUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 219, 84));

        botonAerolinea.setText("Aerolinea");
        botonAerolinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAerolineaActionPerformed(evt);
            }
        });
        jPanel1.add(botonAerolinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 219, 84));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/general/fondoIngresoEmpresa.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(816, 816, 816))
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        add(base, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void botonUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonUsuariosActionPerformed
        // TODO add your handling code here:

        InterfazInicioUsuario ingresoInterUsuarios = new InterfazInicioUsuario();
        ingresoInterUsuarios.setSize(1300, 570);
        ingresoInterUsuarios.setLocation(base.getLocation());

        this.base.removeAll();
        this.base.add(ingresoInterUsuarios, BorderLayout.CENTER);
        this.base.revalidate();
        this.base.repaint();
    }//GEN-LAST:event_botonUsuariosActionPerformed

    private void botonAerolineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAerolineaActionPerformed
        // TODO add your handling code here:
        InterIngresoAerolinea ingresoInterEmpleados = new InterIngresoAerolinea();
        ingresoInterEmpleados.setSize(1300, 570);
        ingresoInterEmpleados.setLocation(base.getLocation());

        this.base.removeAll();
        this.base.add(ingresoInterEmpleados, BorderLayout.CENTER);
        this.base.revalidate();
        this.base.repaint();
    }//GEN-LAST:event_botonAerolineaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JButton botonAerolinea;
    private javax.swing.JButton botonUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
